services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Dedeepya@02
      MYSQL_DATABASE: patientdb2
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here
    networks:
      - springboot-mysql-net
    

  backend:
    image: 2300030813/docker-backend:latest
    container_name: springboot
    build:
      context: ./PATIENTAPI-SPRINGBOOT
      dockerfile: ../PATIENTAPI-FULLSTACK/backend.Dockerfile
    ports:
      - "1810:1900"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: 2300030813/docker-frontend:latest
    container_name: react
    build:
      context: ./PATIENTAPI-REACT
      dockerfile: ../PATIENTAPI-FULLSTACK/frontend.Dockerfile
    ports:
      - "1820:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

    
# Declare volumes at the bottom
volumes:
  mysql-data:
networks:
  springboot-mysql-net:

